:PROPERTIES:
:ID:       1aa632ef-587c-4d13-9b30-92a1c258dd5f
:END:
#+title: cloud computing

Cloud computing is the on-demand delivery of compute power, database storage, applications, and other IT resources through a cloud services platform via the Internet with pay-as-you-go pricing.

Cloud computing provides a simple way to access servers, storage, databases, and a broad set of application services over the Internet.

* Advantages of cloud
:PROPERTIES:
:ID:       467395a6-31c2-4f32-afcb-4d79da7542f9
:END:
You must understand the following 6 advantages of cloud:
1. Trade capital expense for variable expense.
2. Benefit from massive economies of scale.
3. Stop guessing about capacity.
4. Increase speed and agility.
5. Stop spending money running and maintaining data centers.
6. Go global in minutes.

** TRADE CAPITAL EXPENSE FOR VARIABLE EXPENSE
Instead of having to invest heavily in data centers and servers before you know how you’re going to use them, you can pay only when you consume computing resources, and pay only for how much you consume.

** BENEFIT FROM MASSIVE ECONOMIES OF SCALE
By using cloud computing, you can achieve a lower variable cost than you can get on your own. Because usage from hundreds of thousands of customers is aggregated in the cloud, cloud providers can achieve higher economies of scale, which translates into lower pay as-you-go price.

** STOP GUESSING ABOUT CAPACITY
Eliminate guessing on your infrastructure capacity needs. When you make a capacity decision prior to deploying an application, you often end up either sitting on expensive idle resources or dealing with limited capacity. With cloud computing, these problems go away. You can access as much or as little capacity as you need and scale up and down as required with only a few minutes’ notice.

** INCREASE SPEED AND AGILITY
In a cloud computing environment, new IT resources are only a click away, which means that you reduce the time to make those resources available to your developers from weeks to just minutes. This results in a dramatic increase in agility for the organization since the cost and time it takes to experiment and develop is significantly lower.

** STOP SPENDING MONEY RUNNING AND MAINTAINING DATA CENTERS
Focus on projects that differentiate your business, not the infrastructure. Cloud computing lets you focus on your own customers, rather than on the heavy lifting of racking, stacking, and powering servers.

** GO GLOBAL IN MINUTES
Easily deploy your application in multiple regions around the world with just a few clicks. This means you can provide lower latency and a better experience for your customers at minimal cost.

* Cloud computing models
:PROPERTIES:
:ID:       957b16e9-99fe-4017-a246-99cf3f08806c
:END:
There are 3 common types of cloud computing model:
1. [[id:90e4969f-1c41-4451-88ad-4959561473ec][Infrastructure as a service (IaaS)]].
2. [[id:83918a70-3722-4c43-9103-e1d42412bebe][Platform as a service (PaaS)]].
3. [[id:1e4094e3-9183-4879-94d3-267fa2d3107a][Software as a Service (SaaS)]].
Reference link: https://digitalcloud.training/cloud-computing-service-models-iaas-paas-saas/

* Types of cloud deployment
:PROPERTIES:
:ID:       28766209-838c-418f-9992-034dc43c643c
:END:
There are 3 common types of cloud deployment:
1. [[id:aa20119a-0616-47c0-8250-da622f6ec60b][Public Cloud]] – e.g. AWS, Microsoft Azure, Google Cloud Platform (GCP).
2. [[id:95f60fde-c21f-4c11-adc0-003b696e9106][Hybrid Cloud]]Hybrid Cloud – a mixture of public and private clouds.
3. [[id:1988535e-9c15-4464-aa96-061b051e4370][Private Cloud (on-premises)]] – a cloud managed in your own data center, e.g. Hyper-V, OpenStack, VMware.
Reference link: https://digitalcloud.training/cloud-computing-deployment-models/

