:PROPERTIES:
:ID:       6795991e-6e79-40f8-a72c-28e23b3d10ef
:END:
#+title: Container Runtimes
#+filetags: container runtimes

* What is container
:PROPERTIES:
:ID:       f328bbb2-b333-49fe-873c-0eadf0a91f3f
:END:
Containers are a lightweight alternative to fully [[id:605f9bc6-7c2d-4ce0-91d3-b001f279323e][Virtual Machine]](VMs). They use the kernel of the host system that they run on, instead of emulating a full operating system (OS). This means that containers can access resources on the host system directly.

The runtime costs for containers is low, usually negligible. However, there are some drawbacks that need be considered:
+ Only Linux distributions can be run in Containers. It is not possible to run other operating systems like, for example, FreeBSD or Microsoft Windows inside a container.
+ For security reasons, access to host resources needs to be restricted. Therefore, containers run in their own separate namespaces. Additionally some syscalls (user space requests to the Linux kernel) are not allowed within containers.

* [[id:b60301a4-574f-43ee-a864-15f5793ea990][Kubernetes]] 
Several common container runtimes with [[id:b60301a4-574f-43ee-a864-15f5793ea990][Kubernetes]]
+ [[id:e4fa2843-dc6e-4303-a209-40df1bd10a0f][docker]]
+ [[id:3bcaed88-479f-4566-951f-b2fdb77eadcf][containerd]]
+ [[id:01bbbfa5-43aa-4bd6-9d4a-44c50a1db6cb][CRI-O]]

* System Containers
+ [[id:2c382716-6c15-4385-945f-e5f64e0c0b6e][LXC]]
  
* Reference List
1. https://kubernetes.io/docs/setup/production-environment/container-runtimes/
