:PROPERTIES:
:ID:       a34ce0b9-4e35-4eab-ab20-79b2ce96522b
:END:
#+title: Wireless Adhoc Network
#+filetags:

A wireless ad-hoc network is a wireless network deployed without any framework or infrastructure. This incorporates wireless mesh networks, mobile ad-hoc networks, and vehicular ad-hoc networks. Its history could be traced back to the Defense Advanced Research Project Agency (DARPA) and Packet Radio Networks (PRNET) which evolved into the Survival Adaptive Radio Networks (SARNET) program. Wireless ad-hoc networks, in particular [[id:207bddea-2583-4a75-ac16-80207005389e][mobile ad-hoc networks (MANET)]], are growing very fast as they make communication simpler and progressively accessible. In any case, their conventions or protocols will in general be hard to structure due to topology dependent behavior of wireless communication, and their distribution and adaptive operations to topology dynamism. They are allowed to move self-assertively at any time. So, the network topology of MANET may change randomly and rapidly at unpredictable times. This makes routing difficult because the topology is continually changing and nodes cannot be expected to have steady data storage.

* Reference List
1. https://www.geeksforgeeks.org/introduction-of-mobile-ad-hoc-network-manet/
