:PROPERTIES:
:ID:       34236e33-876e-4520-aa0e-da6f3b4b10bc
:END:
#+title: AWS Lambda

[[id:dcf5e347-8a8a-4c63-a822-53f558025f8c][AWS]]

AWS Lambda is a [[id:a48b2650-4a85-4f91-b7d7-dde90fb45639][serverless computing]] technology that allows you to run code without provisioning or managing servers.

AWS Lambda executes code only when needed and scales automatically.

You pay only for the compute time you consume (you pay nothing when your code is not running).

Benefits of AWS Lambda:
+ No servers to manage.
+ Continuous scaling.
+ Millisecond billing.
+ Integrates with almost all other AWS services.
 
Primary use cases for AWS Lambda:
+ Data processing.
+ Real-time file processing.
+ Real-time stream processing.
+ Build serverless backends for web, mobile, IOT, and 3rd party API requests.

* [[id:c86ab8d3-fefe-4081-8221-79c1b5b7b472][Pricing]]
Pay only for what you use and charged based on the number of requests for functions and the time it takes to execute the code.
Price is dependent on the amount of memory allocated to the function.

