:PROPERTIES:
:ID:       4831fd0c-dbbc-4112-addb-827d44bf16b3
:END:
#+title: AWS CloudTrail

AWS CloudTrail is a web service that records activity made on your account and delivers log files to an Amazon S3 bucket.

CloudTrail is for auditing ([[id:203cb959-208a-4abe-8fc4-8eb80f6e6770][Amazon CloudWatch]] is for performance monitoring).

CloudTrail is about logging and saves a history of API calls for your AWS account.

Provides visibility into user activity by recording actions taken on your account.

API history enables security analysis, resource change tracking, and compliance auditing.

Logs API calls made via:
+ AWS Management Console.
+ AWS SDKs.
+ Command line tools.
+ Higher-level AWS services (such as CloudFormation).
  
CloudTrail records account activity and service events from most AWS services and logs the following records:
+ The identity of the API caller.
+ The time of the API call.
+ The source IP address of the API caller.
+ The request parameters.
+ The response elements returned by the AWS service.
  
CloudTrail is enabled by default.

CloudTrail is per AWS account.

You can consolidate logs from multiple accounts using an S3 bucket:
1. Turn on CloudTrail in the paying account.
2. Create a bucket policy that allows cross-account access.
3. Turn on CloudTrail in the other accounts and use the bucket in the paying account.
   
You can integrate CloudTrail with CloudWatch Logs to deliver data events captured by CloudTrail to a CloudWatch Logs log stream.

CloudTrail log file integrity validation feature allows you to determine whether a CloudTrail log file was unchanged, deleted, or modified since CloudTrail delivered it to the specified [[id:bc7360d3-a192-48ca-83e8-d856b7edee99][Amazon Simple Storage Service (S3)]] bucket.


