:PROPERTIES:
:ID:       f42f4ed2-84df-463a-bae7-eb043421742c
:END:
#+title: Create Users in Linux
#+filetags:  

* useradd Command
The general syntax for the useradd command is as follows:
#+begin_src bash
useradd [OPTIONS] USERNAME
#+end_src
Only root or users with sudo privileges can use the useradd command to create new user accounts.

When invoked, useradd creates a new user account according to the options specified on the command line and the default values set in the /etc/default/useradd file.

The variables defined in this file differ from distribution to distribution, which causes the useradd command to produce different results on different systems.

useradd also reads the content of the /etc/login.defs file. This file contains configuration for the shadow password suite such as password expiration policy, ranges of user IDs used when creating system and regular users, and more.

* How to Create a New User in Linux
To create a new user account, invoke the useradd command followed by the name of the user.

For example to create a new user named username you would run:
#+begin_src bash
sudo useradd username
#+end_src

When executed without any option, useradd creates a new user account using the default settings specified in the /etc/default/useradd file.
The command adds an entry to the /etc/passwd, /etc/shadow, /etc/group and /etc/gshadow files.

To be able to log in as the newly created user, you need to set the user password. To do that run the passwd command followed by the username:
#+begin_src bash
sudo passwd username
#+end_src

You will be prompted to enter and confirm the password. Make sure you use a strong password.
#+begin_src console

Changing password for user username.
New password:
Retype new password:
passwd: all authentication tokens updated successfully.
#+end_src

* How to Add a New User and Create Home Directory
On most Linux distributions, when creating a new user account with useradd, the user’s home directory is not created.

Use the -m (--create-home) option to create the user home directory as /home/username:
#+begin_src bash
sudo useradd -m username
#+end_src
The command above creates the new user’s home directory and copies files from /etc/skel directory to the user’s home directory. If you list the files in the /home/username directory, you will see the initialization files:

#+begin_src console
ls -la /home/username/
drwxr-xr-x 2 username username 4096 Dec 11 11:23 .
drwxr-xr-x 4 root     root     4096 Dec 11 11:23 ..
-rw-r--r-- 1 username username  220 Apr  4  2018 .bash_logout
-rw-r--r-- 1 username username 3771 Apr  4  2018 .bashrc
-rw-r--r-- 1 username username  807 Apr  4  2018 .profile
#+end_src

Within the home directory, the user can write, edit and delete files and directories.

* Adding User to the [[id:b48da282-af6f-4668-9592-db9cc83bbea0][sudo]] Group
On Ubuntu, the easiest way to grant sudo privileges to a user is by adding the user to the “sudo” group. Members of this group can execute any command as root via sudo and prompted to authenticate themselves with their password when using sudo.

We’re assuming that the user already exists. If you want to create a new user, check this guide.

To add the user to the group run the command below as root or another sudo user. Make sure you change “username” with the name of the user that you want to grant permissions to.
#+begin_src bash
usermod -aG sudo username
#+end_src

Granting sudo access using this method is sufficient for most use cases.

To ensure that the user has sudo privileges, run the whoami command:
#+begin_src bash
sudo whoami
#+end_src

You will be prompted to enter the password. If the user has sudo access, the command will print “root”:
#+begin_src file
root
#+end_src

If you get an error saying “user is not in the sudoers file”, it means that the user doesn’t have sudo privileges.

* Remove a Linux user
Switch to the root user:
#+begin_src bash
sudo su -
#+end_src

Use the userdel command to remove the old user:
#+begin_src bash
userdel user's username
#+end_src

Optional: You can also delete that user's home directory and mail spool by using the -r flag with the command:
#+begin_src bash
userdel -r user's username
#+end_src

* Reference List
1. https://linuxize.com/post/how-to-create-users-in-linux-using-the-useradd-command/
