:PROPERTIES:
:ID:       cc4d5749-c647-406e-a08d-ef4850406219
:END:
#+title: ns3
#+filetags:

Today, there are several competitive as well as feature-rich network simulators available in the market for researchers, each with its own strengths and merits [2]. Many of these are capable of not only modeling traditional wired networks but also cutting-edge technologies such as Wi-Fi and 5G networks [2].

NS-3 is a popular discrete-event network [[id:7ba901b0-7d4c-4d02-b35c-7eef502447c0][simulation software]], targeted primarily for research and educational use. NS-3 provides a complex and rich library for the simulation of wireless and wired technology. There are two main benefits:
+ It supports the integrations with other open-source software, thus reducing the requirement for rewriting simulation models.
+ It can be used to simulate and analyze large-scale network simulations very efficiently [3, 4]. The protocols are designed to closely model realistic scenario computations and devices.

* NS 3 Installation
[[id:2210ac49-a9e6-4a08-9e1f-8ee5b39e6d8d][ns3 installation]]

* NS 3 config
[[id:4d2a426a-90b4-491f-b6de-d49ab8ebad83][ns3 TraceSources]]

* Projects
+ [[id:a63c6ec6-a812-4694-b777-3d83a2286725][Anomaly Prediction]]

* Reference List
1. https://www.nsnam.org/about/
2. Walia, A. K., Chhabra, A., & Sharma, D. (2022). Comparative Analysis of Contemporary Network Simulators. In Innovative Data Communication Technologies and Application: Proceedings of ICIDCA 2021 (pp. 369-383). Singapore: Springer Nature Singapore.
3. Bilalb, S. M., & Othmana, M. (2013). A performance comparison of network simulators for wireless networks. arXiv preprint arXiv:1307.4129.
4. Pan, J., & Jain, R. (2008). A survey of network simulation tools: Current status and future developments. Email: jp10@ cse. wustl. edu, 2(4), 45.
