:PROPERTIES:
:ID:       4404e28d-812d-427c-aa9e-bbbf095686ef
:END:
#+title: AWS Cost Calculators and Tools

[[id:dcf5e347-8a8a-4c63-a822-53f558025f8c][AWS]]
[[id:c86ab8d3-fefe-4081-8221-79c1b5b7b472][AWS Billing and Pricing]]

AWS Cost Calculators and Tools
+ AWS Cost Explorer – enables you to visualize your usage patterns over time and to identify your underlying cost drivers.
+ AWS Pricing Calculator – create cost estimates to suit your AWS use cases.

* AWS Cost Explorer
The AWS Cost Explorer is a free tool that allows you to view charts of your costs.
You can view cost data for the past 13 months and forecast how much you are likely to spend over the next three months.
Cost Explorer can be used to discover patterns in how much you spend on AWS resources over time and to identify cost problem areas.

Cost Explorer can help you to identify service usage statistics such as:
+ Which services you use the most.
+ View metrics for which AZ has the most traffic.
+ Which linked account is used the most.

* AWS Pricing Calculator
AWS Pricing Calculator is a web-based service that you can use to create cost estimates to suit your AWS use cases.
AWS Pricing Calculator is useful both for people who have never used AWS and for those who want to reorganize or expand their usage.
AWS Pricing Calculator allows you to explore AWS services based on your use cases and create a cost estimate.

