:PROPERTIES:
:ID:       b84f629e-a395-4056-bdf0-f15602224d38
:END:
#+title: USB mount tools
#+filetags:

Please, use udiskctl.
[[id:7e6372d3-24f6-48e9-b745-1594312cdac9][mount usb with udiskctl]]

pcmanfm

* Identify the USB drive using the lsblk command
#+begin_src bash
lsblk
#+end_src
* Create a directory to mount the USB drive into.
When an external drive is automatically mounted it is often mounted inside the media directory. However using the CLI we can create and specify a directory into which we will mount our pendrive.

*Note* that we need to evoke root privileges using sudo to create a directory inside the media directory.

#+begin_src bash
sudo mkdir /media/pendrive
#+end_src

* Mount the USB
Mount the USB drive to the /media/pendrive directory using the mount command. The mount command has the following syntax; sudo mount /path/to/drive /path/to/mountpoint.

#+begin_src bash
sudo mount /dev/sdb1 /media/pendrive
#+end_src

* Unmounting a drive in Linux using the umount command
Unmounting a drive is handled via the umount command and when invoked it safely removes the drive from the system, enabling us to pull the drive and use it in another machine.

1. Unmount the drive using umount command. Note the spelling of umount as a common error is people type “unmount”. Using the umount command we only need to specify the mount point location and name of the drive we wish to unmount.
   #+begin_src bash
sudo umount /media/pendrive
   #+end_src

