:PROPERTIES:
:ID:       ed03a348-8a07-44b4-97ac-2f6c608ed896
:END:
#+title: association rule mining

Association rules are used to find the relationships between the objects which are frequently used together.

There are two basic criteria that association rules uses, support and .confidence. It identifies the relationships and rules generated by analyzing data for frequently used if/then patterns.

Association rules are usually needed to satisfy a user-specified minimum support and a user -specified minimum confidence at the same time.

Here are the definitions:

1. **Support**: This is a measure of how often the items in $X$ and $Y$ occur together as a percentage of the total number of transactions. In the equation:

   $\text{Support} = \frac{\text{freq}(X, Y)}{N}$

   $\text{freq}(X, Y)$ is the frequency or count of how often $X$ and $Y$ occur together in the dataset, and $N$ is the total number of transactions or records in the dataset.

2. **Confidence**: This is a measure of how often items in $Y$ are likely to be purchased or seen when $X$ has occurred. It is calculated by the equation:

   $\text{Confidence} = \frac{\text{freq}(X, Y)}{\text{freq}(X)}$

   Here, $\text{freq}(X)$ is the frequency or count of how often $X$ occurs in the dataset. 

The rule $X \Rightarrow Y$ in this context implies that whenever $X$ occurs, $Y$ is likely to occur as well. These types of rules are often used in market basket analysis to identify relationships between the purchase of different products.

+ [[id:3f4435db-dd60-40e5-b9b1-57473da353e6][AIS algorithm]]
+ [[id:c4d76bcc-1b01-48ac-aa22-afb2679e20a1][SETM algorithm]]
+ [[id:535827be-f93f-476d-b8df-4ab8bb2701bd][apriori]]
+ [[id:8b277e08-0dfc-4cd6-87c2-3d2854958dd6][APRIORI-SD]] 
+ [[id:dbe981e1-8f24-4215-b6f6-1ec0a2f83a58][aprioritid]]
+ [[id:0fec921f-82e1-4462-9c4d-7b5199f7bf04][apriorihybrid]]
+ [[id:3e01722d-90af-41bf-aad7-98f9423761a2][FP-growth algorithm]]
  
* Reference list
1. Kumbhare, T. A., & Chobe, S. V. (2014). An overview of association rule mining algorithms. International Journal of Computer Science and Information Technologies, 5(1), 927-930.
