:PROPERTIES:
:ID:       91ce7793-c4cb-4d28-bc30-1fc4e0939e74
:END:
#+title: Amazon Elastic Kubernetes Service (EKS)

[[id:dcf5e347-8a8a-4c63-a822-53f558025f8c][AWS]]

[[id:b60301a4-574f-43ee-a864-15f5793ea990][Kubernetes]]

Amazon Elastic Container Service for Kubernetes (EKS) is a managed Kubernetes service that makes it easy for you to run Kubernetes on AWS without needing to install, operate, and maintain your own Kubernetes control plane.

EKS is certified Kubernetes conformant, so existing applications running on upstream Kubernetes are compatible with Amazon EKS.

EKS automatically manages the availability and scalability of the Kubernetes control plane nodes that are responsible for starting and stopping containers, scheduling containers on virtual machines, storing cluster data, and other tasks.

EKS automatically detects and replaces unhealthy control plane nodes for each cluster.

Generally available but only in limited regions currently.

* Reference List
1. https://aws.amazon.com/eks/features/
   
