:PROPERTIES:
:ID:       aad50733-22b0-42e9-9f12-9f544fc52bb5
:END:
#+title: github ssh key

[[id:b091635c-19ca-4bf6-88c3-a672a46dc66d][ssh key]]

[[id:29337d81-6b02-4a62-bd87-6e9d5d454af4][github]]

* Generating a new SSH key and adding it to the ssh-agent
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key
#+begin_src bash
  ssh-keygen -t ed25519 -C "your_email@example.com"
#+end_src

* Adding your SSH key to the ssh-agent
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent
Before adding a new SSH key to the ssh-agent to manage your keys, you should have checked for existing SSH keys and generated a new SSH key.
Start the ssh-agent in the background.
#+begin_src bash
$ eval "$(ssh-agent -s)"
> Agent pid 59566
#+end_src
Depending on your environment, you may need to use a different command. For example, you may need to use root access by running sudo -s -H before starting the ssh-agent, or you may need to use exec ssh-agent bash or exec ssh-agent zsh to run the ssh-agent.

Add your SSH private key to the ssh-agent.

If you created your key with a different name, or if you are adding an existing key that has a different name, replace id_ed25519 in the command with the name of your private key file.
#+begin_src bash
ssh-add ~/.ssh/id_ed25519
#+end_src
Add the SSH public key to your account on GitHub.
