:PROPERTIES:
:ID:       2a3bfdcc-4049-411c-89e0-1d47be248320
:END:
#+title: Clustering Algorithms

Clustering, as the basic composition of data analysis, plays a significant role.
each clustering algorithm has its own strengths and weaknesses, due to the complexity of information.

* process of clustering
1. Feature extraction and selection: extract and select the most representative features
from the original data set;
2. Clustering algorithm design: design the clustering algorithm according to the
characteristics of the problem;
3. Result evaluation: evaluate the clustering result and judge the validity of algorithm;
4. Result explanation: give a practical explanation for the clustering result;

* common similarity and distance measurements
[[id:cab89017-0c22-494f-8d15-030a64037e76][Distance Metrics]]
[[id:88fb4715-79e6-487f-adfe-59142eb4d0a3][Similarity functions]]

* Types of Clustering
Several approaches to clustering exist. For an exhaustive list, see [[https://link.springer.com/article/10.1007/s40745-015-0040-1][A Comprehensive Survey of Clustering Algorithms Xu, D. & Tian, Y. Ann. Data. Sci. (2015)]] 2: 165. Each approach is best suited to a particular data distribution. Below is a short discussion of four common approaches, focusing on centroid-based clustering using k-means.

+ [[id:3956d11e-6a94-4f47-8b82-9d5d66e11d63][Centroid-based/Partition-based Clustering]]
+ [[id:be2cb1b4-34ed-49f8-8e7a-1b75d6a37f8e][Hierarchical Clustering]]
+ [[id:64db6b8c-4212-4fe4-bbe4-f199b3946836][Density-based Clustering]]
+ [[id:3d0ade0b-6012-47ad-8a0f-5b1e97703671][Distribution-based Clustering]]

* Result evaluation
[[id:9fa6c501-730e-446e-b4c3-2dc35f30a9de][evaluation indicators]]

* Reference List
1. https://developers.google.com/machine-learning/clustering/clustering-algorithms
   
