:PROPERTIES:
:ID:       270ff2b9-c454-4435-b581-00db1d24e38f
:END:
#+title: Security vs. Privacy
#+filetags:  

The main difference between [[id:56e1bcab-97ff-4fbe-acdf-9573a142d697][privacy]] and [[id:278645d6-efd7-4127-a748-e309c118efbe][security]] is that privacy involves how your data is used and controlled, while security protects this data. Security can exist without privacy, but the reverse is not true. Computer security and privacy are both equally important for managing personal and sensitive information and data. In general, privacy refers to details about you directly and how you wish to share them. Security keeps you safe from potential threats. Cybersecurity, therefore, involves securing data from unauthorized use or access. In terms of data, privacy refers directly to how companies are able to collect, manage, store, and control the use of data that you provide. Personal privacy has often been considered a luxury not available to everyone, while security has long been deemed essential. Public security has regularly been valued over privacy; however, a lack of personal privacy can become a public security issue. While different, security and privacy both need to be maintained.

* Reference List
1. https://www.okta.com/identity-101/privacy-vs-security/#:~:text=Privacy%20is%20the%20right%20to,against%20hackers%20or%20cyber%20criminals.
