:PROPERTIES:
:ID:       43b9eff4-03f0-4263-9ad8-b8004a452f26
:END:
#+title: wireless sensor network (WSN)
#+filetags:

Wireless Sensor Network: A wireless sensor network can be characterized as a system of devices, indicated as nodes that can detect the environment and impart the data accumulated from the monitored field (e.g., a zone or volume) through remote or wireless connections. It can be depicted as a system of nodes that agreeably sense and may control the environment enabling association between people or computers and the surrounding environment. The information is sent, possibly through different jumps, to a sink (indicated as a controller or monitor) that can utilize it locally or is associated with different systems (e.g., The Internet) through a portal. The nodes can be fixed or moved.

* Applications:
+ Environmental Monitoring
+ Health Care
+ Positioning and Monitoring

* Reference List
1. https://www.geeksforgeeks.org/differences-between-wireless-adhoc-network-and-wireless-sensor-network/
