:PROPERTIES:
:ID:       1aa014cf-13ee-4f4c-a1dd-ed750bf22cc8
:END:
#+title: feature selection

Feature selection (FS) methods can be used in data pre-processing to achieve efficient data reduction. This is useful for finding accurate data models.

The usual applications of FS are in [[id:ca712e09-e52d-4a74-b794-dc514e126e50][classification]], [[id:2a3bfdcc-4049-411c-89e0-1d47be248320][Clustering]], and [[id:c69367ef-05db-4d51-b6fe-4d066c432358][regression]] tasks.

* why
The problem is important, because a high number of features in a dataset, comparable to or higher than the number of samples, leads to model overfitting, which in turn leads to poor results on the validation datasets. [1]

[[id:5c72122d-7c00-4e3e-81fc-7ca2c86bdf01][random feature search]]

* Reference List
1. Jović, A., Brkić, K., & Bogunović, N. (2015, May). A review of feature selection methods with applications. In 2015 38th international convention on information and communication technology, electronics and microelectronics (MIPRO) (pp. 1200-1205). Ieee.
