:PROPERTIES:
:ID:       bdc27a9c-6f72-4b51-ac1c-d511af9f3c0f
:END:
#+title: Amazon EMR

Amazon EMR is a web service that enables businesses, researchers, data analysts, and developers to process vast amounts of data easily and cost-effectively.

EMR utilizes a hosted [[id:89ffb30b-234e-47e5-8bab-a14cfb016062][Hadoop]] framework running on [[id:f92ab341-b10b-4ec5-9034-e124dda3f081][AWS EC2]] and [[id:bc7360d3-a192-48ca-83e8-d856b7edee99][Amazon Simple Storage Service (S3)]].

Managed Hadoop framework for processing huge amounts of data.

Also support Apache Spark, [[id:ba3d2f11-e107-4d15-9aa5-38e68ccd3911][Apache HBase]], Presto and [[id:394ba301-aac1-4f7a-8ead-44744e602934][flink]].

Most commonly used for log analysis, financial analysis, or extract, translate and loading (ETL) activities.

A Step is a programmatic task for performing some process on the data (e.g. count words).

A cluster is a collection of EC2 instances provisioned by EMR to run your Steps.

EMR uses Apache Hadoop as its distributed data processing engine, which is an open source, Java software framework that supports data-intensive distributed applications running on large clusters of commodity hardware.

EMR is a good place to deploy Apache Spark, an open-source distributed processing used for big data workloads which utilizes in-memory caching and optimized query execution.

You can also launch Presto clusters. Presto is an open-source distributed SQL query engine designed for fast analytic queries against large datasets.

EMR launches all nodes for a given cluster in the same Amazon EC2 Availability Zone.

You can access Amazon EMR by using the AWS Management Console, Command Line Tools, SDKS, or the EMR API.

With EMR you have access to the underlying operating system (you can [[id:428988ba-6665-49f8-8f84-3138f076f021][ssh]] in).

