:PROPERTIES:
:ID:       7f82ddc1-f703-4677-b2fa-fa75af944640
:END:
#+title: ftatistical relational learning (SRL)
Statistical Relational Learning (SRL) is a subdiscipline of artificial intelligence and [[id:b1cf8bef-07d8-44c4-bb19-c3362a74463f][machine learning]] that is concerned with domain models that exhibit both uncertainty (which can be dealt with using statistical methods) and complex, relational structure.

Note that SRL is sometimes called Relational Machine Learning (RML) in the literature.

Typically, the [[id:72485e34-a45e-4c8c-a6ff-beb0647a10aa][Knowledge representation]] formalisms developed in SRL use (a subset of) [[id:62a88943-3bee-4ff4-be2f-87d87b32dfcd][first-order logic]] to describe relational properties of a domain in a general manner (universal quantification) and draw upon probabilistic graphical models (such as Bayesian networks or Markov networks) to model the uncertainty; some also build upon the methods of inductive logic programming. Significant contributions to the field have been made since the late 1990s.

As is evident from the characterization above, the field is not strictly limited to learning aspects; it is equally concerned with [[id:91554788-4dbd-4e5d-82f6-6509aac8fb7f][reasoning]] (specifically probabilistic inference) and knowledge representation. Therefore, alternative terms that reflect the main foci of the field include statistical relational learning and reasoning (emphasizing the importance of reasoning) and first-order probabilistic languages (emphasizing the key properties of the languages with which models are represented).

SRL systems typically support the learning of the SRL model from data, and support the ability to answer queries using [[id:511c7df2-096a-4a59-bc8a-cdf14bffea27][probabilistic inference]].

* Canonical tasks
+ link-based [[id:2a3bfdcc-4049-411c-89e0-1d47be248320][clustering]], i.e. the grouping of similar objects, where similarity is determined according to the links of an object, and the related task of collaborative filtering, i.e. the filtering for information that is relevant to an entity (where a piece of information is considered relevant to an entity if it is known to be relevant to a similar entity)

+ [[id:dea7a3b1-0396-422f-92df-b2dc89efdeb1][Markov Logic Networks (MLN)]] [4]
  
* Book
+ Introduction to Statistical Relational Learning (Adaptive Computation and Maching Learning) by Lise Getoor (Editor)
  
* Reference List
1. https://blog.csdn.net/PolarisRisingWar/article/details/127395263
2. https://en.wikipedia.org/wiki/Statistical_relational_learning
3. Getoor, L., & Mihalkova, L. (2011, June). Learning statistical models from relational data. In Proceedings of the 2011 ACM SIGMOD International Conference on Management of data (pp. 1195-1198).
4. Khosravi, H., & Bina, B. (2010). A survey on statistical relational learning. In Advances in Artificial Intelligence: 23rd Canadian Conference on Artificial Intelligence, Canadian AI 2010, Ottawa, Canada, May 31–June 2, 2010. Proceedings 23 (pp. 256-268). Springer Berlin Heidelberg.
   
