:PROPERTIES:
:ID:       e61a48d9-bb5e-44c3-820b-6542ae2f04d4
:END:
#+title: srsRAN

[[id:058d9d70-dbbd-4d7d-bd6c-84ddd80c42a6][5G deployment modes]]

* Introduction
:PROPERTIES:
:ID:       5005b4b9-5034-4326-89c5-807a7361ef8d
:END:
srsRAN is an open source radio access network project used to build and test software-defined 4G and 5G systems. In the current 5G-focused context, the =srsRAN_Project= is most relevant as a gNB implementation with CU/DU deployment options and integration paths to open 5G cores such as [[id:ccd1542a-488e-430d-9eba-f24c01c26bbe][Open5GS]].

It is especially useful for lab environments, private-network experimentation, and interoperability testing with commercial UEs, USB modems, and O-RAN-style deployments.

* Resources
:PROPERTIES:
:ID:       43676d5b-3e38-4391-a2ea-39cba6df4257
:END:
+ [[https://github.com/srsran/srsRAN_Project][srsRAN Project repository]]
+ [[https://docs.srsran.com/projects/project/en/latest/][srsRAN Project documentation]]
+ [[https://docs.srsran.com/projects/project/en/latest/user_manuals/source/installation.html#manual-installation][Manual installation guide]]
+ [[https://docs.srsran.com/projects/project/en/latest/tutorials/source/k8s/source/index.html][gNB on Kubernetes tutorial]]

* 5G CU/DU solution
:PROPERTIES:
:ID:       4c7f75d3-63a1-403a-9977-dfe484e789f9
:END:
The srsRAN Project provides a 5G gNB implementation that can be deployed using CU/DU separation. This makes it a practical fit for split-RAN experimentation, edge deployments, and integration work with open radio units and external 5G cores.

Related notes:
+ [[id:af84dc9d-61ec-4a73-b738-bd2048e4a56a][CU (Central Unit)]]
+ [[id:225aa706-2680-46e9-8111-4eedbb0b28f4][Distributed Unit (DU)]]
