:PROPERTIES:
:ID:       526c4f39-0de6-4273-a353-beb774585c14
:END:
#+title: MLflow Recipes

MLflow Recipes (previously known as MLflow Pipelines) is a framework that enables data scientists to quickly develop high-quality models and deploy them to production.

* Recipe Templates
MLflow Recipes currently offers the following predefined templates that can be easily customized to develop and deploy high-quality, production-ready models for your use cases:
+ MLflow Recipes [[https://github.com/mlflow/recipes-regression-template.git][Regression Template]]: The MLflow Recipes Regression Template is designed for developing and scoring regression models. For more information, see the Regression Template reference guide.
+ MLflow Recipes [[https://github.com/mlflow/recipes-classification-template.git][Classification Template]]: The MLflow Recipes Classification Template is designed for developing and scoring classification models. For more information, see the Classification Template reference guide.
  
* MLflow Recipes Examples
Note: This example repo is intended for first-time MLflow Recipes users to learn its fundamental concepts and workflows. For users already familiar with MLflow Recipes, find a template repository to solve a specific ML problem. For example, for regression problem, use recipes-regression-template instead.

* Reference List
1. https://mlflow.org/docs/latest/recipes.html#recipe-templates
