:PROPERTIES:
:ID:       81b73ee5-9d2b-4f0c-abd3-ef55b2f77a32
:END:
#+title: LILYGO
#+date: 2025-06-10

* T-Beam SUPREME
https://lilygo.cc/products/t-beam-supreme?variant=43067954135221
https://lilygo.cc/products/t-beam-supreme-meshtastic?variant=45315788046517

Channel 0, LongFast. Be sure your psi is set to AQ==

* 3D Printing
[[id:1dbd761e-231d-4615-854d-374ef2b5282b][UVA 3D printing]]
** Lilygo T-Beam SUPREME TS2 Case
+ https://www.printables.com/model/959441-lilygo-t-beam-supreme-ts2-case-by-alley-cat
+ https://www.youtube.com/watch?v=-4vdjDpvhfU
  
+ https://www.printables.com/model/565428-lilygo-ttgo-t-beam-supreme-case

* Flashing Firmware
** Flashing Method for ESP32 Devices
+ The Web Flasher requires either Chrome or Edge browsers but is an excellent choice for quickly flashing devices. This method is highly recommended for firmware flashing, especially for new users of the project, as it is easy to use.
+ The CLI Script is considered the "manual process" for flashing firmware.
+ Flashing your device using an external serial adapter should only be attempted as a last resort if no other method has been successful.
*** Flashing with the CLI
https://meshtastic.org/docs/getting-started/flashing-firmware/esp32/cli-script/
**** Install Prerequisite Software
Update packages
#+begin_src bash
sudo pacman -Syu
#+end_src
**** Install Python 3 and pip
#+begin_src bash
sudo pacman -S python python-pip
python --version
pip --version
# (python3/pip3 are usually symlinks; try them if you need)
python3 --version
pip3 --version
#+end_src
**** Install esptool
#+begin_src bash
sudo pacman -S esptool
#+end_src

**** Verify
#+begin_src bash
esptool --help
#+end_src
**** Serial port access without sudo
On Arch, USB serial devices belong to the uucp group.
#+begin_src bash
sudo usermod -aG uucp,lock "$USER"
newgrp uucp  # or log out/in
#+end_src
**** Confirm Communication With Chip
#+begin_src console
Connected to ESP32-S3 on /dev/ttyACM0:
Chip type:          ESP32-S3 (QFN56) (revision v0.2)
Features:           Wi-Fi, BT 5 (LE), Dual Core + LP Core, 240MHz, Embedded Flash 8MB (GD)
Crystal frequency:  40MHz
USB mode:           USB-Serial/JTAG
MAC:                64:e8:33:60:31:78

Stub flasher running.

Warning: ESP32-S3 has no chip ID. Reading MAC address instead.
MAC:                64:e8:33:60:31:78

Hard resetting via RTS pin...
#+end_src
*** Download Firmware
1. Head to the [[https://meshtastic.org/downloads/][Meshtastic Downloads Page]] to download the latest firmware.
2. Scroll down to the Firmware section and select one of the following, depending on your preferences:
3. Download Stable: For stable, well-tested releases.
4. Download Alpha: For newer, experimental releases with the latest features.
5. Once redirected to the GitHub release page, scroll down to the "Assets" section and expand it. Identify the correct firmware for your device by its architecture (e.g., firmware-esp32s3 for ESP32-S3-based devices like the Heltec V3).
6. Download the file and take note of the download location on your system (usually in your ~/Downloads folder).

*** Install/Update Firmware
#+begin_src bash
unzip firmware-esp32s3-2.6.11.60ec05e.zip
#+end_src
Install
#+begin_src bash
./device-install.sh -f firmware-tbeam-s3-core-2.6.11.60ec05e.bin
#+end_src
Update
#+begin_src bash
./device-update.sh -f firmware-tbeam-s3-core-2.6.11.60ec05e-update.bin
#+end_src

*** T-Beam Hardware Buttons
https://meshtastic.org/docs/hardware/devices/lilygo/tbeam/buttons/?t-beam=t-beam-supreme
* Setting

* Reference List
1. https://store.rokland.com/pages/t-beam-supreme-getting-started-quick-guide-meshtastic?srsltid=AfmBOoqz06wcJwr6YaCfXm_9hIv-CyicM6WMmp4ND-KiHiuTY_wcX0Wf
2. https://meshtastic.org/docs/configuration/
