:PROPERTIES:
:ID:       605f9bc6-7c2d-4ce0-91d3-b001f279323e
:END:
#+title: Virtual Machine
#+filetags: Virtual Machine

* What is a virtual machine?
A Virtual Machine (VM) is a compute resource that uses software instead of a physical computer to run programs and deploy apps. One or more virtual “guest” machines run on a physical “host” machine.  Each virtual machine runs its own operating system and functions separately from the other VMs, even when they are all running on the same host. This means that, for example, a virtual MacOS virtual machine can run on a physical PC.

Virtual machine technology is used for many use cases across on-premises and cloud environments. More recently, public cloud services are using virtual machines to provide virtual application resources to multiple users at once, for even more cost efficient and flexible compute.

* What are virtual machines used for?
Virtual machines (VMs) allow a business to run an operating system that behaves like a completely separate computer in an app window on a desktop. VMs may be deployed to accommodate different levels of processing power needs, to run software that requires a different operating system, or to test applications in a safe, sandboxed environment.

Virtual machines have historically been used for server virtualization, which enables IT teams to consolidate their computing resources and improve efficiency. Additionally, virtual machines can perform specific tasks considered too risky to carry out in a host environment, such as accessing virus-infected data or testing operating systems. Since the virtual machine is separated from the rest of the system, the software inside the virtual machine cannot tamper with the host computer.

* How do virtual machines work?
The virtual machine runs as a process in an application window, similar to any other application, on the operating system of the physical machine. Key files that make up a virtual machine include a log file, NVRAM setting file, virtual disk file and configuration file.

* Advantages of virtual machines
+ Virtual machines are easy to manage and maintain, and they offer several advantages over physical machines:
+ VMs can run multiple operating system environments on a single physical computer, saving physical space, time and management costs.
Virtual machines support legacy applications, reducing the cost of migrating to a new operating system. For example, a Linux virtual machine running a distribution of Linux as the guest operating system can exist on a host server that is running a non-Linux operating system, such as Windows.
+ VMs can also provide integrated disaster recovery and application provisioning options.

* Disadvantages of virtual machines
While virtual machines have several advantages over physical machines, there are also some potential disadvantages:

+ Running multiple virtual machines on one physical machine can result in unstable performance if infrastructure requirements are not met.
+ Virtual machines are less efficient and run slower than a full physical computer. Most enterprises use a combination of physical and virtual infrastructure to balance the corresponding advantages and disadvantages.

* The two types of virtual machines
Users can choose from two different types of virtual machines—process VMs and system VMs:

+ A *process virtual machine* allows a single process to run as an application on a host machine, providing a platform-independent programming environment by masking the information of the underlying hardware or operating system. An example of a process VM is the Java Virtual Machine, which enables any operating system to run Java applications as if they were native to that system.

+ A *system virtual machine* is fully virtualized to substitute for a physical machine. A system platform supports the sharing of a host computer’s physical resources between multiple virtual machines, each running its own copy of the operating system. This virtualization process relies on a hypervisor, which can run on bare hardware, such as VMware ESXi, or on top of an operating system.

** System Virtual Machine Management Platform
+ [[id:cf2c18b4-f9a0-412f-825f-11a0e837dab5][OpenStack]]
+ [[id:e6303bdc-b166-486e-8e76-f45b619a376b][multipass]]

* Reference List
1. https://www.vmware.com/topics/glossary/content/virtual-machine.html
