:PROPERTIES:
:ID:       9d349422-b1b5-4ab9-93c7-db5970477ebc
:END:
#+title: display chinese characters
#+filetags:  

[[id:dc13b67c-8d8b-40fd-b8cf-9ea8547e485d][Arch Linux]]

* Install Chinese locale
It is recommended to use UTF-8 locale. You need to modify */etc/locale.gen* to set the locales that can be used in the system (erase the comment symbol "#" before the corresponding item):
#+begin_src file
en_US.UTF-8 UTF-8
zh_CN.UTF-8 UTF-8
#+end_src

After executing *locale-gen*, the selected locales can be used in the system. You may use locale to view the currently used locale(s), and *locale -a* to view the currently available locales.

* Enable Chinese locales
User-specific locales
You may set your own user environment variables in ~/.bashrc, ~/.xinitrc, or ~/.xprofile.

.bashrc: Settings are applied everytime you log in using the terminal.
.xinitrc: Settings are applied everytime you use startx or SLiM to start the X interface.
.xprofile: Settings are applied everytime you log in using a display manager such as GDM.

It is not recommended to set a global Chinese locale in /etc/locale.conf because it causes tty to display garbled characters.

As mentioned earlier, Chinese locale can be set separately in ~/.xinitrc or ~/.xprofile. Prepend the following two lines to one of the two files (if you are not sure which file to use, prepend to both):

#+begin_src file
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US
#+end_src

* Reference List
1. https://wiki.archlinux.org/title/Localization/Simplified_Chinese
