:PROPERTIES:
:ID:       d5e3306d-b96e-47a5-a146-b1fab0a645b4
:END:
#+title: Prometheus Operator vs. kube-prometheus vs. community helm chart
#+filetags:  

* [[id:23fbb8d6-424d-4cd0-8cea-cbef874f583e][Prometheus Operator]]
The Prometheus Operator uses Kubernetes custom resources to simplify the deployment and configuration of Prometheus, Alertmanager, and related monitoring components.

* [[id:76d59c83-05cd-4bd0-a794-4a38473b487b][kube-prometheus]]
kube-prometheus provides example configurations for a complete cluster monitoring stack based on Prometheus and the Prometheus Operator. This includes deployment of multiple Prometheus and Alertmanager instances, metrics exporters such as the node_exporter for gathering node metrics, scrape target configuration linking Prometheus to various metrics endpoints, and example alerting rules for notification of potential issues in the cluster.

* [[id:12001e11-f40c-4e7b-8a99-50695ae37d2e][helm chart]]
The prometheus-community/kube-prometheus-stack helm chart provides a similar feature set to kube-prometheus. This chart is maintained by the Prometheus community.
