:PROPERTIES:
:ID:       bf4517d9-d2d7-437f-ae23-3bc3adc89b72
:END:
#+title: MetalLB
#+filetags:

MetalLB is a load-balancer implementation for bare metal [[id:b60301a4-574f-43ee-a864-15f5793ea990][Kubernetes]] clusters, using standard routing protocols.

* Why?
Kubernetes does not offer an implementation of network load balancers (Services of type LoadBalancer) for bare-metal clusters. The implementations of network load balancers that Kubernetes does ship with are all glue code that calls out to various IaaS platforms (GCP, AWS, Azure…). If you’re not running on a supported IaaS platform (GCP, AWS, Azure…), LoadBalancers will remain in the “pending” state indefinitely when created.

Bare-metal cluster operators are left with two lesser tools to bring user traffic into their clusters, “NodePort” and “externalIPs” services. Both of these options have significant downsides for production use, which makes bare-metal clusters second-class citizens in the Kubernetes ecosystem.

MetalLB aims to redress this imbalance by offering a network load balancer implementation that integrates with standard network equipment, so that external services on bare-metal clusters also “just work” as much as possible.

* Installation With [[id:fd2a4c2f-4d5f-43b8-aab8-69b1ae33870e][Helm]]
You can install MetallLB with Helm by using the Helm chart repository: https://metallb.github.io/metallb
#+begin_src bash
helm repo add metallb https://metallb.github.io/metallb
helm install metallb metallb/metallb
#+end_src

A values file may be specified on installation. This is recommended for providing configs in Helm values:
#+begin_src bash
helm install metallb metallb/metallb -f values.yaml
#+end_src

* Reference List
1. https://www.youtube.com/watch?v=Yl8JKffmhuE&ab_channel=VirtualizationHowto
