:PROPERTIES:
:ID:       9e6faa6f-06f4-497b-83d2-69ad2ff749d1
:END:
#+title: Deep learning-based data privacy protection in software-defined
#+filetags: privacy

software-defined industrial networks (SDIN)

This study suggests a deep [[id:d4f709b9-ba62-4d0a-af70-289b8a7b34d7][Differential Privacy]] data protection algorithm based on SDIN.

The deep learning model is analyzed and integrated with differential privacy to provide the process framework for the deep differential privacy data protection algorithm.

* Current Method


The equivalent model of the generative adversarial network is used to allow the attacker to obtain the optimal fake samples.

The balance between dataset availability and privacy protection is achieved by implementing parameter tuning on the deep differential privacy model.

The experimental results show that the proposed algorithm has strong industrial data privacy protection and high data availability and can effectively guarantee the privacy security of industrial data.

For now, most of the data privacy protection in the IIoT is mathematical encryption to ensure the privacy of the original data. From the perspective of the data producer (factory or user), the data generated by the terminal is usually mathematically encrypted and then transmitted to the corresponding receiver or uploaded to the server for calculation processing.

The release and analysis of sensitive data is where differential privacy is most frequently used. Differential privacy protection provides a thorough definition and quantitative evaluation of the strength of privacy protection without considering the attacker’s prior knowledge [7].

Machine learning aims to extract information from the data distribution, not just from individual data. This is also the goal of differentially private data release, that is, to reveal the overall dataset distribution containing private information rather than the information of any single individual in the dataset.

Therefore, differential privacy and deep learning have a profound theoretical basis. Before deep learning became popular, there was much research on the combination of machine learning and differential privacy protection [8]. Fortunately, differential privacy introduces random interference into machine learning algorithms. In this way, differential privacy can protect privacy at the cost of reducing the accuracy of the machine learning model. In contrast, deep learning consumes many computing and communication resources, while differential privacy has low computing requirements.

Therefore, the deep learning of privacy protection based on differential privacy is exceptionally suitable for the current big data
analysis, especially for the data privacy protection in the SDIN studied in this paper.

the main contribution of this paper is that a deep differential privacy data protection algorithm is proposed to protect the privacy security of industrial data under SDIN.



* Reference List
1. Wu, W., Qi, Q., & Yu, X. (2023). Deep learning-based data privacy protection in software-defined industrial networking. Computers and Electrical Engineering, 106, 108578.
